create sequence option_seq start with 1 increment by 50;
create sequence question_seq start with 1 increment by 50;
create sequence quiz_seq start with 1 increment by 50;
create table option (is_answer boolean not null, id bigint not null, caption varchar(255), primary key (id));
create table question (id bigint not null, caption varchar(255), primary key (id));
create table question_options (options_id bigint not null unique, question_id bigint not null);
create table quiz (id bigint not null, name varchar(255), subject varchar(255) check (subject in ('MATH','HISTORY','ENGLISH','IT')), topic varchar(255), primary key (id));
create table quiz_questions (questions_id bigint not null unique, quiz_id bigint not null);
alter table if exists question_options add constraint FKe58cbk9s8i39o4lgjlhfptsf2 foreign key (options_id) references option;
alter table if exists question_options add constraint FKjk4v42xhyfv4ca1yyhorsg5tv foreign key (question_id) references question;
alter table if exists quiz_questions add constraint FKpmfvwer12y1nrjc0efm04dq16 foreign key (questions_id) references question;
alter table if exists quiz_questions add constraint FKcgp9e1c6ww3t383aui4w8feae foreign key (quiz_id) references quiz;
create sequence option_seq start with 1 increment by 50;
create sequence question_seq start with 1 increment by 50;
create sequence quiz_seq start with 1 increment by 50;
create table option (is_answer boolean not null, id bigint not null, caption varchar(255), primary key (id));
create table question (id bigint not null, caption varchar(255), primary key (id));
create table question_options (options_id bigint not null unique, question_id bigint not null);
create table quiz (id bigint not null, name varchar(255), subject varchar(255) check (subject in ('MATH','HISTORY','ENGLISH','IT')), topic varchar(255), primary key (id));
create table quiz_questions (questions_id bigint not null unique, quiz_id bigint not null);
alter table if exists question_options add constraint FKe58cbk9s8i39o4lgjlhfptsf2 foreign key (options_id) references option;
alter table if exists question_options add constraint FKjk4v42xhyfv4ca1yyhorsg5tv foreign key (question_id) references question;
alter table if exists quiz_questions add constraint FKpmfvwer12y1nrjc0efm04dq16 foreign key (questions_id) references question;
alter table if exists quiz_questions add constraint FKcgp9e1c6ww3t383aui4w8feae foreign key (quiz_id) references quiz;
