version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgresContainer
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aiQuizDB

